################################# CAMBIA ROMANOS POR ARÁBIGOS ##############################
#         Cambia los cifras romanas por arábigas en la numeración de capítulos             #
#         se ha de examinar cómo aparecen en el texto o serie de textos en los             #
#                 se ha de convertir y modificar el patrón de búsqueda.                    #

#  Proyecto 7PartidasDigital "Edición crítica digital de las Siete Partidas de Alfonso X"  #
#        Proyecto financiado por el MINECO, referencia FFI2016-75014-P AEI-FEDER, EU       #
#                Universidad de Valladolid -- IP José Manuel Fradejas Rueda                #
#                              https://7partidas.hypotheses.org/                           #
#                             https://github.com/7PartidasDigital                          #
#                         Este material se distribuye con una licencia                     #
#                                            MIT                                           #
#                                         v. 1.0.0                                         #

# Ojo al directorio de trabajo y nombres de fichero de entrada y salida
setwd("~/Desktop/TEST/test")

ficheros <- list.files()
for (i in 1:length(ficheros)){
texto <- readLines(ficheros[i])
texto <- gsub("^– I –$", "– 1 –", texto, perl = T)
texto <- gsub("^– II –$", "– 2 –", texto, perl = T)
texto <- gsub("^– III –$", "– 3 –", texto, perl = T)
texto <- gsub("^– IV –$", "– 4 –", texto, perl = T)
texto <- gsub("^– V –$", "– 5 –", texto, perl = T)
texto <- gsub("^– VI –$", "– 6 –", texto, perl = T)
texto <- gsub("^– VII –$", "– 7 –", texto, perl = T)
texto <- gsub("^– VIII –$", "– 8 –", texto, perl = T)
texto <- gsub("^– IX –$", "– 9 –", texto, perl = T)
texto <- gsub("^– X –$", "– 10 –", texto, perl = T)
texto <- gsub("^– XI –$", "– 11 –", texto, perl = T)
texto <- gsub("^– XII –$", "– 12 –", texto, perl = T)
texto <- gsub("^– XIII –$", "– 13 –", texto, perl = T)
texto <- gsub("^– XIV –$", "– 14 –", texto, perl = T)
texto <- gsub("^– XV –$", "– 15 –", texto, perl = T)
texto <- gsub("^– XVI –$", "– 16 –", texto, perl = T)
texto <- gsub("^– XVII –$", "– 17 –", texto, perl = T)
texto <- gsub("^– XVIII –$", "– 18 –", texto, perl = T)
texto <- gsub("^– XIX –$", "– 19 –", texto, perl = T)
texto <- gsub("^– XX –$", "– 20 –", texto, perl = T)
texto <- gsub("^– XXI –$", "– 21 –", texto, perl = T)
texto <- gsub("^– XXII –$", "– 22 –", texto, perl = T)
texto <- gsub("^– XXIII –$", "– 23 –", texto, perl = T)
texto <- gsub("^– XXIV –$", "– 24 –", texto, perl = T)
texto <- gsub("^– XXV –$", "– 25 –", texto, perl = T)
texto <- gsub("^– XXVI –$", "– 26 –", texto, perl = T)
texto <- gsub("^– XXVII –$", "– 27 –", texto, perl = T)
texto <- gsub("^– XXVIII –$", "– 28 –", texto, perl = T)
texto <- gsub("^– XXIX –$", "– 29 –", texto, perl = T)
texto <- gsub("^– XXX –$", "– 30 –", texto, perl = T)
texto <- gsub("^– XXXI –$", "– 31 –", texto, perl = T)
texto <- gsub("^– XXXII –$", "– 32 –", texto, perl = T)
texto <- gsub("^– XXXIII –$", "– 33 –", texto, perl = T)
texto <- gsub("^– XXXIV –$", "– 34 –", texto, perl = T)
texto <- gsub("^– XXXV –$", "– 35 –", texto, perl = T)
texto <- gsub("^– XXXVI –$", "– 36 –", texto, perl = T)
texto <- gsub("^– XXXVII –$", "– 37 –", texto, perl = T)
texto <- gsub("^– XXXVIII –$", "– 38 –", texto, perl = T)
texto <- gsub("^– XXXIX –$", "– 39 –", texto, perl = T)
texto <- gsub("^– XL –$", "– 40 –", texto, perl = T)
texto <- gsub("^– XLI –$", "– 41 –", texto, perl = T)
texto <- gsub("^– XLII –$", "– 42 –", texto, perl = T)
texto <- gsub("^– XLIII –$", "– 43 –", texto, perl = T)
texto <- gsub("^– XLIV –$", "– 44 –", texto, perl = T)
texto <- gsub("^– XLV –$", "– 45 –", texto, perl = T)
texto <- gsub("^– XLVI –$", "– 46 –", texto, perl = T)
texto <- gsub("^– XLVII –$", "– 47 –", texto, perl = T)
texto <- gsub("^– XLVIII –$", "– 48 –", texto, perl = T)
texto <- gsub("^– XLIX –$", "– 49 –", texto, perl = T)
texto <- gsub("^– L –$", "– 50 –", texto, perl = T)
texto <- gsub("^– LI –$", "– 51 –", texto, perl = T)
texto <- gsub("^– LII –$", "– 52 –", texto, perl = T)
texto <- gsub("^– LIII –$", "– 53 –", texto, perl = T)
texto <- gsub("^– LIV –$", "– 54 –", texto, perl = T)
texto <- gsub("^– LV –$", "– 55 –", texto, perl = T)
texto <- gsub("^– LVI –$", "– 56 –", texto, perl = T)
texto <- gsub("^– LVII –$", "– 57 –", texto, perl = T)
texto <- gsub("^– LVIII –$", "– 58 –", texto, perl = T)
texto <- gsub("^– LIX –$", "– 59 –", texto, perl = T)
texto <- gsub("^– LX –$", "– 60 –", texto, perl = T)
texto <- gsub("^– LXI –$", "– 61 –", texto, perl = T)
texto <- gsub("^– LXII –$", "– 62 –", texto, perl = T)
texto <- gsub("^– LXIII –$", "– 63 –", texto, perl = T)
texto <- gsub("^– LXIV –$", "– 64 –", texto, perl = T)
texto <- gsub("^– LXV –$", "– 65 –", texto, perl = T)
texto <- gsub("^– LXVI –$", "– 66 –", texto, perl = T)
texto <- gsub("^– LXVII –$", "– 67 –", texto, perl = T)
texto <- gsub("^– LXVIII –$", "– 68 –", texto, perl = T)
texto <- gsub("^– LXIX –$", "– 69 –", texto, perl = T)
texto <- gsub("^– LXX –$", "– 70 –", texto, perl = T)
texto <- gsub("^– LXXI –$", "– 71 –", texto, perl = T)
texto <- gsub("^– LXXII –$", "– 72 –", texto, perl = T)
texto <- gsub("^– LXXIII –$", "– 73 –", texto, perl = T)
texto <- gsub("^– LXXIV –$", "– 74 –", texto, perl = T)
texto <- gsub("^– LXXV –$", "– 75 –", texto, perl = T)
texto <- gsub("^– LXXVI –$", "– 76 –", texto, perl = T)
texto <- gsub("^– LXXVII –$", "– 77 –", texto, perl = T)
texto <- gsub("^– LXXVIII –$", "– 78 –", texto, perl = T)
texto <- gsub("^– LXXIX –$", "– 79 –", texto, perl = T)
texto <- gsub("^– LXXX –$", "– 80 –", texto, perl = T)
texto <- gsub("^– LXXXI –$", "– 81 –", texto, perl = T)
texto <- gsub("^– LXXXII –$", "– 82 –", texto, perl = T)
texto <- gsub("^– LXXXIII –$", "– 83 –", texto, perl = T)
texto <- gsub("^– LXXXIV –$", "– 84 –", texto, perl = T)
texto <- gsub("^– LXXXV –$", "– 85 –", texto, perl = T)
texto <- gsub("^– LXXXVI –$", "– 86 –", texto, perl = T)
texto <- gsub("^– LXXXVII –$", "– 87 –", texto, perl = T)
texto <- gsub("^– LXXXVIII –$", "– 88 –", texto, perl = T)
texto <- gsub("^– LXXXIX –$", "– 89 –", texto, perl = T)
texto <- gsub("^– XC –$", "– 90 –", texto, perl = T)
texto <- gsub("^– XCI –$", "– 91 –", texto, perl = T)
texto <- gsub("^– XCII –$", "– 92 –", texto, perl = T)
texto <- gsub("^– XCIII –$", "– 93 –", texto, perl = T)
texto <- gsub("^– XCIV –$", "– 94 –", texto, perl = T)
texto <- gsub("^– XCV –$", "– 95 –", texto, perl = T)
texto <- gsub("^– XCVI –$", "– 96 –", texto, perl = T)
texto <- gsub("^– XCVII –$", "– 97 –", texto, perl = T)
texto <- gsub("^– XCVIII –$", "– 98 –", texto, perl = T)
texto <- gsub("^– XCIX –$", "– 99 –", texto, perl = T)
texto <- gsub("^– C –$", "– 100 –", texto, perl = T)
write(texto, ficheros[i])
}
